import localFont from "next/font/local";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const morabba = localFont({
  src: [
    {
      path: "../public/fonts/Morabba/webfont/fonts/woff2/Morabba-Light.woff2",
      weight: "300",
    },
    {
      path: "../public/fonts/Morabba/webfont/fonts/woff2/Morabba-Regular.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/Morabba/webfont/fonts/woff2/Morabba-Medium.woff2",
      weight: "500",
    },
    {
      path: "../public/fonts/Morabba/webfont/fonts/woff2/Morabba-SemiBold.woff2",
      weight: "600",
    },
    {
      path: "../public/fonts/Morabba/webfont/fonts/woff2/Morabba-Bold.woff2",
      weight: "700",
    },
  ],
});
const iranSansX = localFont({
  variable: "--font-iran-sans-x",
  src: [
    {
      path: "../public/fonts/IRANSansX/Woff2/IRANSansXFaNum_Light.woff2",
      weight: "300",
    },
    {
      path: "../public/fonts/IRANSansX/Woff2/IRANSansXFaNum_Regular.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/IRANSansX/Woff2/IRANSansXFaNum_Medium.woff2",
      weight: "500",
    },
    {
      path: "../public/fonts/IRANSansX/Woff2/IRANSansXFaNum_Bold.woff2",
      weight: "700",
    },
  ],
});
// const peyda = localFont({
//   variable: "--font-peyda",
//   src: [
//     {
//       path: "../public/fonts/Peyda-3/woff2/PeydaWeb-Light.woff2",
//       weight: "300",
//     },
//     {
//       path: "../public/fonts/Peyda-3/woff2/PeydaWeb-Regular.woff2",
//       weight: "400",
//     },
//     {
//       path: "../public/fonts/Peyda-3/woff2/PeydaWeb-Medium.woff2",
//       weight: "500",
//     },
//   ],
// });

import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "@/components/providers/react-query";
import RecoilProvider from "@/components/providers/recoil";
import RootProvider from "@/components/providers/root";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${morabba.className} ${iranSansX.variable} ${inter.variable}`}
        // className={`${morabba.className} ${iranSansX.variable} ${inter.variable} ${peyda.variable}`}
        dir="rtl"
      >
        <RootProvider>
          <RecoilProvider>
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </RecoilProvider>
        </RootProvider>
      </body>
    </html>
  );
}
